name: Create Fackel listperson.xml

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Create Fackel listperson.xml
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{secrets.GITLAB_TOKEN}}
      DL_URL: https://gitlab.oeaw.ac.at/api/v4/projects/33/repository/files/fackelnames%2Fxml%2FFK_Persons_131008.xml/raw?ref=master
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install python things
      run: |
        pip install -r requirements.txt
    - name: fetch data
      run: |
        ./fetch_data.sh
    - name: Copy processed data to karl-kraus/fackel-texte
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './data/.'
        destination_repo: 'karl-kraus/fackel-texte'
        destination_folder: 'indices'
        user_email: 'peter.andorfer@oeaw.ac.at.com'
        user_name: 'csae8092'
        commit_message: 'pushed listperson.xml from karl-kraus/fackel-persons'